apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: w3lgspo59-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/w3lgspo59-java-springboot-gitops